# Generated by Django 3.2.5 on 2021-07-09 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trello', '0002_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(blank=True, choices=[('P', 'PENDING'), ('C', 'COMPLETED'), ('IP', 'IN_PROGRESS'), ('D', 'DROPPED')], max_length=2, null=True),
        ),
    ]
